# Generated by Django 5.1.7 on 2025-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('on_hand', 'On-Hand'), ('gcash', 'GCash')], default='on_hand', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(),
        ),
    ]
