# Generated by Django 5.1.7 on 2025-04-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_booking_payment_method_alter_booking_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
    ]
